site_name: tds-core-legacy-v2
site_description: Documentation for tds-core-legacy-v2
plugins:
  - techdocs-core
nav:
  - Forms: Forms.md
  - Lists: Lists.md
  - Icons: icons.md
  - Typography: Typography.md
  - Intro:
      - Welcome: intro/welcome.md
